#server.port 9004

#Eureka
#eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka/

#spring.cloud.gateway.discovery.locator.enabled=true
#spring.cloud.gateway.routes.id=produit
#spring.cloud.gateway.routes.uri=http://localhost:9001/
#spring.cloud.gateway.routes.predicates.Path=/microservice-produit/**

#spring.cloud.discovery.enabled=true

#eureka.instance.hostname=localhost
#eureka.client.register-with-eureka=false
server:
  port: 9004

spring:
  cloud:
    gateway:
      routes:
      - id: produit
        uri: http://localhost:9001/
        predicates:
        - Path=/microservice-produit/**
     






        
      
